### ISSUE TITLE
Not finding connection string with password in AppSettings.json

### ISSUE THREAD

**Issue by shehackspurple** [max/secret-scan#3]
I'm running this in my workflow: https://github.com/shehackspurple/dotnetcore-webapp/blob/master/.github/workflows/DotNetDemo.yml

It's not finding a really obvious password/connection string in my appsettings.JSON file.
https://github.com/shehackspurple/dotnetcore-webapp/blob/master/appsettings.json

Shouldn't it find that?

**Comment by mattlorimor** [comment]
This action simply runs the latest version of [`truffleHog` from pypi](https://pypi.org/project/truffleHog/#history) against the code. Does running _just_ truffleHog (not via this action) against the same code set yield results?

**Comment by mattlorimor** [comment]
If this action isn't finding something you expect it to, it's likely a bug/feature request in the [truffleHog project](https://github.com/dxa4481/truffleHog), not this action.

**Comment by shehackspurple** [comment]
Hi Max. I got Truffle hog working, but this action is giving my incompatibility errors for teh version of Python that it's using.  See here:

Step 10/13 : RUN pip install truffleHog
 ---> Running in b4b9a77dce3a
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting truffleHog
  Downloading truffleHog-2.1.11-py2.py3-none-any.whl (13 kB)
Collecting truffleHogRegexes==0.0.7
  Downloading truffleHogRegexes-0.0.7-py2.py3-none-any.whl (2.5 kB)
ERROR: Could not find a version that satisfies the requirement GitPython==3.0.6 (from truffleHog) (from versions: 0.1.7, 0.2.0b1, 0.3.0b1, 0.3.0b2, 0.3.1b2, 0.3.2rc1, 0.3.2, 0.3.2.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9.dev0, 2.0.9.dev1, 2.0.9, 2.1.0, 2.1.1, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.13, 2.1.14, 2.1.15)
ERROR: No matching distribution found for GitPython==3.0.6 (from truffleHog)
The command '/bin/sh -c pip install truffleHog' returned a non-zero code: 1

##[error]Docker build failed with exit code 1

I feel like maybe you need to update your action so it works with the updated trufflehog action?

Thanks for your response!

**Comment by mattlorimor** [comment]
@shehackspurple - #5 fixes the truffleHog install issue.

**Comment by shehackspurple** [comment]
Cool Matt!  Unfortunately it's still waiting on a review to get into the master branch.  How could I be able to call it now?

**Comment by shehackspurple** [comment]
PS Thanks for your super quick reply!

**Comment by mattlorimor** [comment]
Disclaimer: I have tried none of these solutions, so can't vouch for any of them.

@shehackspurple - I know it's not truffleHog-based, but you could try [this](https://github.com/evanextreme/detect-secrets-action) action which uses Yelp's [Detect Secrets](https://github.com/Yelp/detect-secrets) library until this is fixed.

If you need truffleHog, you could set up your own action to do it. Or, potentially, utilize the truffleHog action shown in the screenshot below with a custom Action Workflow setup in your repo:

![image](https://user-images.githubusercontent.com/1616060/75097706-73c34b00-5573-11ea-8a91-3903ffbd84b0.png)
